#! /bin/sh

. /usr/local/bin/inc

session_expiry=$(expr $(/usr/local/python/policy.py session_expiry) / 30)

find ${BASE}/service/sessions -mmin +${session_expiry} -type f -delete

/usr/local/bin/exec_doms run_mx_check
