#! /bin/sh

this_base="${BASE:-/opt/data}"

svr_pem="${this_base}/pems/server.pem"
svr_dst="run/pems/server.pem"
if test -f ${svr_pem} -a ${svr_pem} -nt ${svr_dst}
	then
		cp -a ${svr_pem} ${svr_dst}
		killall -HUP nginx
		killall stunnel
		postfix reload
	fi
